### ISSUE TITLE
Error when adding module to page

### ISSUE THREAD

**Issue by kurtwilby** [mydnn/LiveChat#2]
When adding module to page, I am getting the following error:

Error: MyDnn Support LiveChat is currently unavailable. DotNetNuke.Services.Exceptions.ModuleLoadException: Type 'ASP._Page_DesktopModules_MVC_MyDnnSupport_LiveChat_Views__ViewStart_cshtml' does not inherit from 'System.Web.WebPages.StartPage'. ---> System.Web.HttpException: Type 'ASP._Page_DesktopModules_MVC_MyDnnSupport_LiveChat_Views__ViewStart_cshtml' does not inherit from 'System.Web.WebPages.StartPage'. at System.Web.UI.Util.CheckAssignableType(Type baseType, Type type) at System.Web.Compilation.BuildManager.CreateInstanceFromVirtualPath(VirtualPath virtualPath, Type requiredBaseType, HttpContext context, Boolean allowCrossApp) at System.Web.WebPages.BuildManagerWrapper.CreateInstanceOfType[T](String virtualPath) at System.Web.WebPages.VirtualPathFactoryManager.CreateInstanceOfType[T](String virtualPath) at System.Web.WebPages.StartPage.GetStartPage(WebPageRenderingBase page, IVirtualPathFactory virtualPathFactory, String appDomainAppVirtualPath, String fileName, IEnumerable`1 supportedExtensions) at System.Web.WebPages.StartPage.GetStartPage(WebPageRenderingBase page, String fileName, IEnumerable`1 supportedExtensions) at System.Web.Mvc.RazorView.RenderView(ViewContext viewContext, TextWriter writer, Object instance) at DotNetNuke.Web.Mvc.Framework.ActionResults.DnnViewResult.ExecuteResult(ControllerContext context, TextWriter writer) at DotNetNuke.Web.Mvc.MvcHostControl.RenderModule(ModuleRequestResult moduleResult) at DotNetNuke.Web.Mvc.MvcHostControl.OnLoad(EventArgs e) --- End of inner exception stack trace ---

**Comment by mydnn** [comment]
Download new version of the module
Fixed this issue 

https://github.com/mydnn/LiveChat/releases/tag/01.02.01
