### ISSUE TITLE
Embeded widgets

### ISSUE THREAD

**Issue by inxcube** [mydnn/LiveChat#5]
Is the livechat possible to embeded into other websites? For example dnn livechat was hosted on subdomain and i want to embed the livechat into my main domain web application as well. Possible?

**Comment by mydnn** [comment]
now a day this is not possible in LiveChat, but in the next release the LiveCaht Module be cross platform and you will can installed the live chat in any website :)

**Comment by inxcube** [comment]
Thank you for your reply. This is great to hear that. So i will wait for your next release..
